version: '2'

networks:
  spark-network:
    driver: bridge

services:
  cassandra:
    image: docker.io/bitnami/cassandra:4.1
    container_name: cassandra-server
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      - "CASSANDRA_CLUSTER_NAME=cassandra-cluster"
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes 
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - ./cassandra_data:/bitnami
    networks:
      - spark-network

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper-server
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper_data:/bitnami
    networks:
      - spark-network
    
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka-server
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper
    volumes:
      - ./kafka_data:/bitnami
    networks:
      - spark-network